### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by xonixx** [xonixx/fhtagn#16]
Blocked by https://github.com/benhoyt/goawk/issues/182

**Comment by benhoyt** [comment]
The GoAWK bug is now fixed by https://github.com/benhoyt/goawk/pull/201 and in GoAWK [v1.24.0](https://github.com/benhoyt/goawk/releases/tag/v1.24.0).

**Comment by xonixx** [comment]
Thank you @benhoyt! I will try the new version.

**Comment by xonixx** [comment]
Thanks all works.
