### ISSUE TITLE
What’s in the name?

### ISSUE THREAD

**Issue by kseistrup** [xonixx/fhtagn#18]
Hm…, what does `fhtagn` stand for? I really want to start using it, but I don't think I'll be able to remember the name. Any mnemonics?

**Comment by xonixx** [comment]
Please see this reply https://lobste.rs/s/bh44j5/fhtagn_tiny_cli_programs_tester_written#c_zwrw5t

**Comment by kseistrup** [comment]
Ah, so it's Lovecraftian. Thanks.

This also tells me where the name “R'lyeh”, that is used in N. K. Jemisin's fantastic novel ”The City We Became”, comes from.
